name: top10Products
description: Quais são os 10 produtos mais vendidos (em quantidade) na categoria "Bicicletas", considerando apenas vendas feitas nos últimos dois anos?
version: 1.0.0

environment:
  sdk: '^3.5.0'

dependencies:
  sqlite3: ^2.4.6